services:
  # Service base de données PostgreSQL
  db:
    image: postgres:15
    container_name: backlog_db
    environment:
      POSTGRES_USER: user_backlog
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: backlog_jeux
    ports:
      - "5432:5432"
    volumes:
      # Volume pour persister les données même si le conteneur est supprimé
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_backlog -d backlog_jeux"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service API Flask
  api:
    build: .
    container_name: backlog_api
    ports:
      - "5000:5000"
    environment:
      # Lien vers la BDD (le nom "db" = nom du service ci-dessus)
      DATABASE_URL: postgresql://user_backlog:motdepasse@db:5432/backlog_jeux
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
      - ./tests:/tests

volumes:
  postgres_data: